config/routes.rb
Rails.application.routes.draw do

  get 'explora' => 'pages#guest', as: :explora
  get 'home' => 'pages#index', as: :home

  devise_for :users
  resources :mailboxes, only: [:index]
  resources :mailboxer_conversations do
    member do
      post :reply
      post :restore
    end

    collection do 
      delete :empty_trash
    end
  end

  get 'mailbox/inbox' => 'mailboxes#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailboxes#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailboxes#trash', as: :mailbox_trash

  resources :comments
  resources :image_posts do 
    resources :comments,only: [:create]
  end

  resources :text_posts do 
    resources :comments,only: [:create]
  end
  
  resources :posts

  resources :users do 
    resources :profiles
    resources :photos
    
    member do 
      post :follow
      delete :unfollow
    end
  end

  root 'posts#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates_associated :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:edit, :update, :destroy]
  layout 'users'

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])
    @user = User.find(@profile)
    @text_post = TextPost.new
  end

  # GET /profiles/new
  def new
    @user = User.find(@profile)
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit
    @user = User.find(@profile)
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = current_user.profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:date_of_birth, :gender, :location, :languages, :bio, :favorite_qoutes, :interest, :favorite_movies, :favorite_music)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.haml
= simple_form_for([user, @profile]) do |f|
  = f.error_notification

  .form-inputs
    = f.input :date_of_birth
    = f.input :gender
    = f.input :location
    = f.input :languages
    = f.input :interest
    = f.input :favorite_movies
    = f.input :favorite_music
    = f.input :bio
    = f.input :favorite_qoutes   

  .form-actions
    = f.button :submit

app/views/profiles/_profile.html.haml
.article
  .well
    %table.table.table-responsive
      %tr
        %th Date Of Birth
        %td= profile.date_of_birth
      %tr
        %th Gender
        %td= profile.gender
      %tr
        %th Location
        %td= profile.location
      %tr
        %th Email
        %td= profile.user.email
      %tr
        %th Languages
        %td= profile.languages
      %tr
        %th Interest
        %td= profile.interest
      %tr
        %th Favorite Movies
        %td= profile.favorite_movies
      %tr
        %th Favorite Music
        %td= profile.favorite_music
      %tr
        %th Favorite Qoutes
        %td= profile.favorite_qoutes
      %tr
        %th Bio
        %td= profile.bio

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form', user: @user

= link_to 'Back', :back

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %thead
    %tr
      %th Date of birth
      %th Location
      %th Languages
      %th Bio
      %th Favorite qoutes
      %th Interest
      %th Favorite movies
      %th Favorite music
      %th Title
      %th
      %th
      %th

  %tbody
    - @profiles.each do |profile|
      %tr
        %td= profile.date_of_birth
        %td= profile.location
        %td= profile.languages
        %td= profile.bio
        %td= profile.favorite_qoutes
        %td= profile.interest
        %td= profile.favorite_movies
        %td= profile.favorite_music
        %td= profile.title
        %td= link_to 'Show', profile
        %td= link_to 'Edit', edit_profile_path(profile)
        %td= link_to 'Destroy', profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
%h1 New profile

= render 'form'

= link_to 'Back', :back

app/views/profiles/show.html.haml
- if current_user and current_user == @user
  %h2= link_to 'Edit Profile', edit_user_profile_path(current_user, @user.profile)
= render @user.profile