config/routes.rb
Rails.application.routes.draw do

  get 'explora' => 'pages#guest', as: :explora
  get 'home' => 'pages#index', as: :home

  devise_for :users
  resources :mailboxes, only: [:index]
  resources :mailboxer_conversations do
    member do
      post :reply
      post :restore
    end

    collection do 
      delete :empty_trash
    end
  end

  get 'mailbox/inbox' => 'mailboxes#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailboxes#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailboxes#trash', as: :mailbox_trash

  resources :comments
  resources :image_posts do 
    resources :comments,only: [:create]
  end

  resources :text_posts do 
    resources :comments,only: [:create]
  end
  
  resources :posts

  resources :users do 
    resources :profiles
    resources :photos
    
    member do 
      post :follow
      delete :unfollow
    end
  end

  root 'posts#index'

end

app/models/text_post.rb
class TextPost < Post
  validates :body, presence: true
end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
  def new
  	@text_post = TextPost.new
  end

  def create
  	@text_post = current_user.text_posts.build(text_post_params)
  	if @text_post.save
  	  redirect_to post_path(@text_post), notice: "Post created!"
  	else
  	  render :new, alert: 'Error creating post.'
  	end
  end

  def edit
  	@text_post = current_user.text_posts.find(params[:id])
  end

  def update
  	@text_post = current_user.text_posts.find(params[:id])
  	if @text_post.update(text_post_params)
  	  redirect_to post_path(@text_post), notice: "Post updated!"
  	else
  	  render :edit, alert: "Error updating post"
  	end
  end

  private
    def text_post_params
      params.require(:text_post).permit(:title, :body)
    end

end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/views/text_posts/_form.html.haml
.article 
  = simple_form_for @text_post do |f|
    = f.input :body, label: false
    .group-btn
      = f.submit 'Text', class: 'btn btn-primary btn-xs'
      = link_to "Image", new_image_post_path, class: 'btn btn-success btn-xs' 

app/views/text_posts/_text_post.html.haml
.well
  .media
    .media-left
      - if text_post.user.photos.present?
        = link_to image_tag(text_post.user.photos.last.image.url(:thumb), width: 64, height: 64, class: 'img-circle'), '#'
      - else
        = image_tag('anon.png', width: 64, height: 64)
    .media-body
      .media-heading
        %h4= link_to text_post.user, user_path(text_post.user)

      %p= text_post.body 
      %p.text-muted= time_ago_in_words(text_post.created_at)

  %hr      
  - if text_post.user == current_user
    %p
      = pluralize text_post.cached_comment_count, "Comment"
      %span.pull-right= link_to 'Edit', edit_text_post_path(text_post), class: 'btn btn-default btn-sm'

app/views/text_posts/edit.html.haml
.page-header
  %h1 Edit Text Post

= render 'form'

app/views/text_posts/new.html.haml
.page-header
  %h1 New Text Post

= render 'form'