config/routes.rb
Rails.application.routes.draw do

  get 'explora' => 'pages#guest', as: :explora
  get 'home' => 'pages#index', as: :home

  devise_for :users
  resources :mailboxes, only: [:index]
  resources :mailboxer_conversations do
    member do
      post :reply
      post :restore
    end

    collection do 
      delete :empty_trash
    end
  end

  get 'mailbox/inbox' => 'mailboxes#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailboxes#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailboxes#trash', as: :mailbox_trash

  resources :comments
  resources :image_posts do 
    resources :comments,only: [:create]
  end

  resources :text_posts do 
    resources :comments,only: [:create]
  end
  
  resources :posts

  resources :users do 
    resources :profiles
    resources :photos
    
    member do 
      post :follow
      delete :unfollow
    end
  end

  root 'posts#index'

end

app/models/image_post.rb
class ImagePost < Post
	has_attached_file :image, styles: {large: "640x480", medium: "320x240", small: "160x120"}
	validates_attachment :image, content_type: {content_type: /\Aimage\/.*\Z/}
end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController

  def new
  	@image_post = ImagePost.new
  end

  def create
  	@image_post = current_user.image_posts.build(image_post_params)

  	if @image_post.save
  	  redirect_to post_path(@image_post), notice: "Image post created!"
  	else
  	  render :new, alert: "Post not created"
  	end
  end

  def edit
  	@image_post = current_user.image_posts.find(params[:id])
  end

  def update
  	@image_post = current_user.image_posts.find(params[:id])
  	if @image_post.update(image_post_params)
  		redirect_to post_path(@image_post), notice: "Post updated!"
  	else
  	    render :edit, alert: "Error updating post."
  	end
  end

  private
    def image_post_params
      params.require(:image_post).permit(:title, :body, :image)
    end
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

app/views/image_posts/_form.html.haml
= simple_form_for @image_post do |f|
  = f.input :image
  = f.input :body
  = f.submit 

app/views/image_posts/_image_post.html.haml
.well
  .media
    .media-left
      - if image_post.user.photos.present?
        = link_to image_tag(image_post.user.photos.last.image.url(:thumb), width: 64, class: 'img-rounded'), '#'
      - else
        = image_tag('anon.png', width: 64)
    .media-body
      .media-heading
        %h4= link_to image_post.user, user_path(image_post.user)

      %p= image_post.body
      %span.thumbnail
        = image_tag image_post.image.url(:medium), class: "img-responsive img-rounded" 

  %hr
    = pluralize image_post.cached_comment_count, "Comment"
    - if image_post.user == current_user 
      %span.pull-right= link_to 'Edit', edit_image_post_path(image_post), class: 'btn btn-sm btn-default'

app/views/image_posts/edit.html.haml
.page-header
  %h1 Edit Image Post

= render 'form'

app/views/image_posts/new.html.haml
.page-header
  %h1 New Image Post

= render 'form'