config/routes.rb
Rails.application.routes.draw do

  get 'explora' => 'pages#guest', as: :explora
  get 'home' => 'pages#index', as: :home

  devise_for :users
  resources :mailboxes, only: [:index]
  resources :mailboxer_conversations do
    member do
      post :reply
      post :restore
    end

    collection do 
      delete :empty_trash
    end
  end

  get 'mailbox/inbox' => 'mailboxes#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailboxes#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailboxes#trash', as: :mailbox_trash

  resources :comments
  resources :image_posts do 
    resources :comments,only: [:create]
  end

  resources :text_posts do 
    resources :comments,only: [:create]
  end
  
  resources :posts

  resources :users do 
    resources :profiles
    resources :photos
    
    member do 
      post :follow
      delete :unfollow
    end
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post, touch: true
  belongs_to :user

  validates :post_id, :user_id, :body, presence: true
end

app/models/image_post.rb
class ImagePost < Post
	has_attached_file :image, styles: {large: "640x480", medium: "320x240", small: "160x120"}
	validates_attachment :image, content_type: {content_type: /\Aimage\/.*\Z/}
end

app/models/photo.rb
class Photo < ActiveRecord::Base
   belongs_to :user
   has_attached_file :image, styles: {medium: '360x240', small: '120x100', thumb: '80x80'}
   validates_attachment :image, content_type: { content_type: /\Aimage\/.*\Z/}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy 
  validates :user_id, presence: true
  validates :type, presence: true

  def cached_comment_count
  	Rails.cache.fetch [self, 'comment_count'] do 
  		comments.size
  	end
  end
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  validates_associated :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :leader, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/text_post.rb
class TextPost < Post
  validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  around_create :create_profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable
  has_many :subscriptions, foreign_key: :follower_id, dependent: :destroy
  has_many :leaders, through: :subscriptions
  has_many :reverse_subscriptions, foreign_key: :leader_id, class_name: 'Subscription', dependent: :destroy
  has_many :followers, through: :reverse_subscriptions

  has_many :posts, dependent: :destroy
  has_many :text_posts, dependent: :destroy
  has_many :image_posts, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_one :profile, dependent: :destroy
  delegate :date_of_birth, :gender, :location, :languages, :bio, :favorite_qoutes, :interest, :favorite_movies, :favorite_music, to: :profile

  has_many :photos, dependent: :destroy

  validates :email, presence: true, uniqueness: true

  def following?(leader)
  	leaders.include? leader
  end

  def follow!(leader)
  	if leader != self && !following?(leader)
  		leaders << leader
  	end
  end

  def unfollow!(leader)
    subscriptions.find_by(leader.id).destroy
  end

  def timeline_user_ids
  	leader_ids + [id]
  end

  def to_s
  	"#{first_name} #{last_name}"
  end

  def mailboxer_email(object)
  	self.email
  end

  def name
  	"#{first_name} #{last_name}"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def guest
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def index
  	user_ids = current_user.timeline_user_ids
  	@posts = Post.includes(:user).where(user_id: user_ids)
  	         .paginate(page: params[:page], per_page: 5).order("created_at DESC")
  	@text_post = TextPost.new
  end

  def show
  	@post = Post.includes(comments: [:user]).find(params[:id])
  	@can_moderate = (current_user == @post.user)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper

	def page_header(text)
		content_for(:page_header) { text.to_s}
	end

	def active_page(active_page)
	  @active == active_page ? 'active' : ''
	end

	def unread_messages_count
	  mailbox.inbox(:unread => true).count(:id, :distinct => true)
	end

	def recipients_options(chosen_recipient = nil)
	  s = ' '
	  User.all.each do |user|
	  	s << "<option value='#{user.id}' #{'selected' if user == chosen_recipient}>#{user.name}</option>"
	  end
	  s.html_safe
	end
	
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_mailboxes_nav.html.haml
%ul.nav.nav-pills.nav-stacked
  %li{ class: active_page(:inbox) }
    = link_to mailbox_inbox_path do 
      %span.label.label-danger.pull-right= unread_messages_count
      %em.fa.fa-inbox.fa-lg
      %span Inbox

  %li{ class: active_page(:sent) }
    = link_to mailbox_sent_path do 
      %em.fa.fa-paper-plane-o.fa-lg
      %span Sent

  %li{class: active_page(:trash) }
    = link_to mailbox_trash_path do 
      %em.fa.fa-trash-o.fa-lg
      %span Trash

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_guest.html.haml
%ul.nav.navbar-nav
  %li= link_to "Explora", explora_path
%ul.nav.navbar-nav.navbar-right
  %li= link_to "Get In", new_user_session_path
  %li= link_to "Register", new_user_registration_path
  %li= link_to "Help", '#'

app/views/layouts/_nav_user.html.haml
%ul.nav.navbar-nav
  %li= link_to "Home", home_path
  -#%li= link_to "Explora", explora_path
%ul.nav.navbar-nav.navbar-right
  %li= link_to 'Mailbox', mailboxes_path, class: 'fa fa-inbox'
  %li.dropdown
    %a#dropdownMenu{ href: user_path(current_user), class:'dropdown-toggle fa fa-user', data: {toggle: 'dropdown'}}
      %i.gyphicon= current_user
      %b.caret
    %ul.dropdown-menu{ role: "menu", aria: {labelledby: "dropdownMenu"}}
      %li= link_to "Profile", user_path(current_user)
      %li= link_to "Help", '#'
      %li= link_to "Edit Profile", edit_user_registration_path
      %li.divider
      %li= link_to "logout", destroy_user_session_path, method: :delete
%form.navbar-form.pull-right
  .group-form
    %input.search-query{ type: "text", placeholder: "Search", class: 'form-control'}
    %button{ type: "submit", class: 'btn btn-default'} search

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Palsmaker', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      - if user_signed_in?
        = render 'layouts/nav_user'
      - else 
        = render 'layouts/nav_guest'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Palsmaker'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Palsmaker'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/layouts/mailboxes.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Palsmaker'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Palsmaker'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main.panel.panel-default{:role => "main"}
      = render 'layouts/messages'
      .row
        .col-md-12
          .page-header
            %h1 Mailbox
            = link_to "Compose", new_mailboxer_conversation_path, class: 'btn btn-success text-right'
        .spacer

        .col-md-4.panel.panel-default
          .panel-body
            = render 'layouts/mailboxes_nav'

        .col-md-8.panel.panel-default
          .panel-body
            = yield

app/views/layouts/users.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Palsmaker'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Palsmaker'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    .row.wrapper
      .col-md-12
        #myCarousel.carousel.slide{ data: {interval: 10000, ride: 'carousel'}}
          %ol.carousel-indicators
            %li.active{ data: {target: "#myCarousel", slide: {to: '0'}}}
            %li{ data: {target: "#myCarousel", slide: {to: '1'}}}
            %li{ data: {target: "#myCarousel", slide: {to: '2'}}}

          .carousel-inner{ role: "listbox"}
            .active.item
              = image_tag('anon.png', alt: 'Packt', class: 'first-slide')
              .container
                .carousel-caption
                  %h6 Major the best
            .item
              = image_tag('a31_001.jpg', alt: 'Packt')
              .conatiner
                .carousel-caption
                  %h6 Major the best
            .item
              = image_tag('Avengers.jpg', alt: 'Packt')
              .container
                .carousel-caption
                  %h6 Major the best

            %a{href: "#myCarousel", class: 'carousel-control left', data: {slide: 'prev'}}
            %a{href: "#myCarousel", class: 'carousel-control right', data: {slide: 'next'}}

      .col-md-12
        .profile_pic
          - if @user.photos.present?
            = image_tag @user.photos.last.image.url(:medium), class: 'thumbnail'
          - else
            = image_tag('anon.png', width: 120)
            
    .row.clearfix
      %ul.nav.nav-tabs.nav-justified
        %li= link_to 'Posts', user_path(@user)
        %li= link_to 'View Profile', user_profile_path(@user, @user.profile)
        %li= link_to 'Photo', user_photo_path(@user, @user.photos)
        %li= link_to 'Following', '#'
        %li= link_to 'Followers', '#'



    %main.clearfix{:role => "main"}
      = render 'layouts/messages'

      .row
        .col-sm-3
          .panel.panel-default
            .panel-body
              %h2
                = @user 
              - if current_user and current_user == @user
                = link_to 'Edit Profile Picture', new_user_photo_path(@user), class: 'btn btn-sm btn-warning'          
              - if user_signed_in?
                - unless current_user == @user 
                  = link_to 'Send message', new_mailboxer_conversation_path(to: @user.id), class: 'btn btn-default'
                - if current_user and @user != current_user
                  - if current_user.following? @user
                    = button_to 'Unfollow', unfollow_user_path(@user), class: "btn btn-danger", method: :delete
                  - else
                    = button_to "Follow", follow_user_path(@user), class: "btn btn-default"

              %h5
                %a{ href: '#', class: 'btn btn-info'}
                  %span.badge= @user.followers.count 
                  followers
                %a{ href: '#', class: 'btn btn-danger pull-right'}
                  following 
                  %span.badge= @user.leaders.count
              = render 'text_posts/form'
        .col-sm-6
          .panel.panel-default
            .panel-heading
              %h3 Recent Posts
            .panel-body
              = yield
        .col-sm-3
          .panel.panel-default
            .panel-body
              About
        .col-sm-3
          .panel.panel-default
            .panel-body
              Trends